### ISSUE TITLE
Comparison with similar packages

### ISSUE THREAD

**Issue by dandv** [VeliovGroup/Meteor-user-status#1]
Hi,

How is this package different from @mizzao's [user-status](https://github.com/mizzao/meteor-user-status) and @dburles's [presence](https://github.com/dburles/meteor-presence/issues/1) packages?

**Comment by mizzao** [comment]
I don't know, but both of these look like evil clones of the originals :)

**Comment by dandv** [comment]
I'm still mystified as to why so many devs come up with alternative packages but don't mention the prior art.

**Comment by dr-dimitru** [comment]
@dandv my package just more simple and work out of the box, no need for additional setup
