### ISSUE TITLE
User Status invalid after Impersonate

### ISSUE THREAD

**Issue by dpatte** [VeliovGroup/Meteor-user-status#2]
I, as a site admin, am using impersonation (masquerade) in order to quickly log in as another user, without having to know their password.
https://dweldon.silvrback.com/impersonating-a-user

This is very handy, and the status shows that the person I log in as is now online.

But when I restore myself to my admin account (by doing a shift-reset), the status of the person I logged in as remains online, until they later log in and out. How would I make its status refresh automatically and return to offline?

**Comment by dr-dimitru** [comment]
Hello @dpatte ,

Thank you for report, this lib was far away from up-to-date.
I've updated library. Please, update it on your end, described issue should be solved, let me know after testing on your end, thank you.

**Comment by dr-dimitru** [comment]
Hi @dpatte 
Let me know if latest update solved this issue, and we can close this ticket

**Comment by dpatte** [comment]
Unfortunately I am on M 1.3.4.1 and cannot seem to update to your latest version

**Comment by dr-dimitru** [comment]
@dpatte well,

Clone this repository into `meteorProj/packages` directory, and change [this line](https://github.com/VeliovGroup/Meteor-user-status/blob/master/package.js#L10) to meet your Meteor version

**Comment by dpatte** [comment]
Busy week, but I'll definitely try that soon and get back to you.

**Comment by dr-dimitru** [comment]
Hello @dpatte ,

Any news on your end?

**Comment by dpatte** [comment]
Tried it last night, but no difference. I suspect it is because cancelling an impersonate is done by Shift-refresh which doesn't trigger the offline functionality.

**Comment by dr-dimitru** [comment]
This lib has two levels to turn user from online to offline status:

 1. On Client if page closed, when user logged out or when connection to server via WebSockets is broken
 2. On server when user logged out or when WebSockets connection is closed

It should work... unless WebSockets conditions left open for some reason

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
