### ISSUE TITLE
Breaking IOS App

### ISSUE THREAD

**Issue by paulincai** [VeliovGroup/Meteor-user-status#3]
Tested with Meteor 1.4.3.2 and 1.4.4.1, react-router and other details are here: https://forums.meteor.com/t/meteor-ios-app-screen-flicker-after-resume-1-4-4-1/35942

Sample here: https://youtu.be/SQDFox62q0A

The status is not right anyway and I was going to remove the package. I installed the packages 2 weeks ago and only recently, after a merge in the master, I noticed the issue and had absolutely no idea where to start. It took me 15 continuous hours of reverting back to older branches and testing progressively until I got this.

All ok now.

**Comment by dr-dimitru** [comment]
Hello @paulincai ,

Thank you for interest to this package.
Accept my apologies for *15 continuous hours* of tinkering.
I'm glad it's solved on your end now.

Could you please give more info on `The status is not right anyway`, what exactly wasn't right?

**Comment by paulincai** [comment]
Hi @dr-dimitru,

thanks for your reply. I don't think you should apologize in any way since this is a community based "offering" and everything is pretty much on an "as is" basis.
If I remember correct, with two mobile phones running the app right in front of me, I could see "away" and "online" switching many times with no relation to the phone status. For example, both phones have the app in foreground, opened in a chat window and status changes from away to online and back without touching the phone.

**Comment by dr-dimitru** [comment]
@paulincai 
Thank you for the reply.

 - Is it Android or iOS?
 - Is it Cordova, Standalone or Web version of an app?
 - Is same user account was logged in on both phones?

**Comment by paulincai** [comment]
@dr-dimitru I am not sure whether the video is still available, that gives a clear picture of what is happening with the app startup.

- the flicker only happened on IOS (latest version on and Iphone 5 and 6 was tested)

- Cordova and web (Chrome). Status changing was similar in web and Cordova, I personally couldn't relate status changing to hardware or browser.

- I normally test a user on an iphone and the other in another iphone + Chrome browser on my Mac

**Comment by dr-dimitru** [comment]
@paulincai got it, thanks for info.

The weird thing - every Cordova and Standalone (on iOS) apps turn into the white background for the 1-3 sec on my end, no matter what packages is used (tested on iPhone 5). My thoughts was - after application is in background mode for few seconds used/reserved memory got flushed, and after you go back to app it has to re-run all JS code

**Comment by paulincai** [comment]
What I noticed with this package installed is that there is some inconsistency in the way the white screen shows up. Let's say it shows 1 in 3 times the app comes back to foreground. It comes whether you send the app to background with the home button take the phone in standby. If you take the phone in standby with the side button, while the app is in foreground chances are you get the screen flash when you come back. The white color is the color of the body background. If you set that to red, the flash will be red.

After I removed the package I just could not get that experience again, everything was fine. MDG confirmed that there should be no flicker or anything, nothing reported in that direction. Android alway worked with no problem.

Now, I use konecty:user-presence. The user status is right, no issues with that. However I have the screen flicker again, not so often and not so long. Every time I get it I can see in the Meteor server console an error related to Push (the package of Raix), something like object query.clocation undefined or so. I am still to finish with this image capture and sending to S3 and then I'll be checking on that.

I use a logger to send to server console every error generated on/by the clients.

**Comment by paulincai** [comment]
@dr-dimitru something I forgot to mention, I am here in case you need me for testing.

**Comment by dr-dimitru** [comment]
@paulincai ,

Does [latest release](https://github.com/VeliovGroup/Meteor-user-status/releases/tag/1.0.0) made a change to original issue?

**Comment by paulincai** [comment]
I don't know cause I am running with konecty and just now I see you have a new version. Anyway I am caught up now with meteor-files to finish this upload with S3 cause it's getting annoying and then I'll take a separate branch into my project and reinstate meteor-user-status

**Comment by dr-dimitru** [comment]
Hello @paulincai ,

Hope you're doing well, haven't heard from you for a while.
Is this one solved?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
