### ISSUE TITLE
Removing jQuery and Underscore dependancy

### ISSUE THREAD

**Issue by appigram** [VeliovGroup/Meteor-user-status#4]
Hey guys, can we remove jQuery and Underscore as a dependency for set event listeners?
We can do smth like this:
```
function addListenersMultiple(el, s, fn) {
  s.split(' ').forEach(e => el.addEventListener(e, fn, false));
}
addListenersMultiple(window, 'mousemove touchmove', functionName);
```
Thanks!

**Comment by dr-dimitru** [comment]
Hello @appigram ,

Thank you for suggestion, done in [`v1.0.1`](https://github.com/VeliovGroup/Meteor-user-status/releases/tag/1.0.1).

Let me know how it works for you.

**Comment by appigram** [comment]
Hi @dr-dimitru,
All works fine.
Thanks for the update!

**Comment by dr-dimitru** [comment]
@appigram great, thank you.
